# Generated by Django 3.0.5 on 2020-04-20 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='comp',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Company'),
        ),
    ]
