# Generated by Django 3.0.5 on 2020-04-20 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200420_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='comp',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='api.Company'),
        ),
    ]
